config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#show", id: 'home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :signups, only: [:new, :create]
  get 'register', to: redirect('/signups/new'), as: :register

  resources :template_message_setups, only: [:new, :create]
  resources :dashboards, only: :index
  resources :static_pages, only: [:show]
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :settings, only: [:edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if logged_in?
      return redirect_to dashboards_path
    end

    render params[:id]
  end
end

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <%= image_tag "logo.png", class: "img-responsive" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <br>

      <p class="lead">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
      </p>

      <p>
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
        tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
        vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
        no sea takimata sanctus est Lorem ipsum dolor sit amet.
      </p>

      <p class="text-center">
        <%= link_to "Sign Up", register_path, class: "btn btn-success" %>
        or
        <%= link_to "Login", login_path, class: "btn btn-warning" %>
      </p>
    </div>
  </div>
</div>