config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#show", id: 'home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :signups, only: [:new, :create]
  get 'register', to: redirect('/signups/new'), as: :register

  resources :template_message_setups, only: [:new, :create]
  resources :dashboards, only: :index
  resources :static_pages, only: [:show]
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :settings, only: [:edit, :update]
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(signup_params)

    if @user.save
      auto_login(@user)
      redirect_to new_template_message_setup_path, notice: "Registration successful! Time to set up your messages!"
    else
      flash.now[:alert] = "Please correct the errors shown and try again"
      render :new
    end

  end

private

  def signup_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :pof_username, :pof_password)
  end
end

app/views/signups/new.html.erb
<div class="container">
  <div class="row">
    <h1>Register</h1>
  </div>

  <%= errors_for(@user) %>

  <div class="row">
    <%= simple_form_for @user, url: signups_path, wrapper: :vertical_form do |f| %>

      <b>Account details</b>
      <%= f.input :email %>
      <%= f.input :password %>

      <br>
      <hr>
      <br>

      <b>POF account details</b>
      <%= f.input :pof_username %>
      <%= f.input :pof_password, as: :string %>
      <%= f.input :name %>

      <%= f.submit "Sign Up", class: "btn btn-default" %>

    <% end %>
  </div>
</div>