config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#show", id: 'home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :signups, only: [:new, :create]
  get 'register', to: redirect('/signups/new'), as: :register

  resources :template_message_setups, only: [:new, :create]
  resources :dashboards, only: :index
  resources :static_pages, only: [:show]
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :settings, only: [:edit, :update]
end

app/views/shared/_form_errors.html.erb
<div class="alert alert-danger">
  <div class="title">Opps! There were some problems.</div>

  <ul>
    <% messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <ul class="nav navbar-nav" style="position: absolute; left: 50%; margin-left: -23px">
      <li class="active">
        <%= link_to dashboards_path do %>
          <span class="glyphicon glyphicon-home"></span>
        <% end %>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Settings", edit_setting_path("interests") %></li>
      <li><%= link_to "Logout", logout_path, method: 'post' %></li>
    </ul>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% if flash[:alert] %>
  <section class="alert alert-warning">
    <div class="container">
      <div class="col-12">
        <p>
          <%= flash[:alert] %>
        </p>
      </div>
    </div>
  </section>
<% end %>

<% if flash[:notice] %>
  <section class="alert alert-success">
    <div class="container">
      <div class="col-12">
        <p>
          <%= flash[:notice] %>
        </p>
      </div>
    </div>
  </section>
<% end %>