config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#show", id: 'home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :signups, only: [:new, :create]
  get 'register', to: redirect('/signups/new'), as: :register

  resources :template_message_setups, only: [:new, :create]
  resources :dashboards, only: :index
  resources :static_pages, only: [:show]
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :settings, only: [:edit, :update]
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  SettingActions = ["messages", "interests"]

  before_action :require_login

  def edit
    raise(ActiveRecord::RecordNotFound) unless SettingActions.include?(params[:id])
    self.send("edit_#{params[:id]}")
  end

  def update
    raise(ActiveRecord::RecordNotFound) unless SettingActions.include?(params[:id])
    self.send("update_#{params[:id]}")
  end

private

  def edit_messages
    @template_messages = current_user.template_messages.where.not(
      state: TemplateMessage::STATE_DISABLED
    )
  end

  def edit_interests
    @interests = Interest.all
  end

  def update_interests
    current_user.update_enabled_interests(
      enabled_interest_ids: params[:interest_ids].map(&:to_i)
    )

    redirect_to edit_setting_path(id: "messages"), notice: "Interests Updated"
  end

  def update_messages
    params[:messages].values.each do |message|
      template_message = current_user.template_messages.find_or_initialize_by(interest: Interest.find(message["interest_id"]))
      template_message.content = message["message"]

      unless template_message.content.present?
        template_message.content_removed! if template_message.may_content_removed?
      end

      template_message.save!
    end

    redirect_to edit_setting_path, id: "messages", notice: "Messages Updated"
  end

end

app/views/settings/_edit_interests.html.erb
<%= simple_form_for :interests, url: setting_path(:interests), method: :put do |f| %>
  <% @interests.in_groups_of(2) do |interest_group| %>
    <div class="row">
      <% interest_group.compact.each do |interest| %>
        <div class="col-sm-4">
          <%= f.input " " do %>
            <label>
              <%= f.check_box :interest_id,
                { name: 'interest_ids[]',
                  checked: current_user.active_interests.include?(interest) },
                interest.id, nil %>
            <%= interest.name %>
            </label>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <%= f.button :submit, "Save" %>
    </div>
  </div>
<% end %>

app/views/settings/_edit_messages.html.erb
<%= simple_form_for :interests, url: setting_path(:messages), method: :put do |f| %>
  <div class="row">
    <% @template_messages.each_with_index do |template_message, idx| %>
      <div class="col-sm-8">
        <%= hidden_field_tag "messages[#{idx}][interest_id]", template_message.interest.id %>
        <%= f.input :messages,
          as: :text,
          label: "Message for #{template_message.interest.name}",
          input_html: {
            name: "messages[#{idx}][message]",
            id: "message-#{template_message.interest.id}",
            value: template_message.content
          } %>
      </div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <%= f.button :submit, "Save" %>
    </div>
  </div>
<% end %>

app/views/settings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <ul class="nav navbar navbar-default navbar-fixed-side">
        <li><%= link_to "Interests", edit_setting_path("interests") %></li>
        <li><%= link_to "Messages", edit_setting_path("messages") %></li>
      </ul>
    </div>

    <div class="col-sm-8 col-sm-offset-1">
      <%= render "edit_#{params[:id]}" %>
    </div>
  </div>

</div>